# Test, and deploy website
language: python
dist: bionic
python:
  - "3.9"

if: branch = master

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_USERNAME/timecapsule:$TRAVIS_BUILD_NUMBER .
  - docker tag $DOCKER_USERNAME/timecapsule:$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/timecapsule:latest
  - docker push $DOCKER_USERNAME/timecapsule # push all tags